import json

# All 52 cooking groups data extracted from PDF
groups_data = [
  {"groupNumber": 1, "captains": ["Ella Vijay Shah", "Smita Ramesh Asher"], "members": ["Ella Vijay Shah", "Geeta Dilip Zaveri", "Hina Rajan Shah", "Kashmira Ketan Shah", "Kokila M. Shah", "Maitri Asher", "Nutan Pradeep Asher", "Pallavi Nirmal Chanderia", "Punita K. Nandola", "Smita Ramesh Asher"]},
  {"groupNumber": 2, "captains": ["Manisha Pandya", "Komal Shah"], "members": ["Amrita Aswin Thakker", "Deepa Prabhu", "Geeta Prakash Raichura", "Kailash Rajesh Modi", "Komal Ravi Shah", "Krishna Sailesh Manek", "Manisha M. Pandya", "Neeta U. Taunk", "Priti Niren Shah", "Vijal Brijesh Vyas"]},
  {"groupNumber": 3, "captains": ["Shobana Pandya", "Bhagyashree"], "members": ["Bhagyashree B. Pandya", "Joshana Akash Trivedi", "Kinjal Jaydeep Joshi", "Pratiksha D Trivedi", "Rita Hitesh Doshi", "Seema K. Pandya", "Shobhana S. Pandya", "Sushila Dinesh Radia", "Usha L Pandya", "Vatsala S. Chothani"]},
  {"groupNumber": 4, "captains": ["Anjana Gajjar", "Manju Kotaliya"], "members": ["Anila Padiyar", "Anjana V. Gajar", "Daya Patel", "Krithikaa Bhatt", "Manjula V. Kantaliya", "Meeta M Talapara", "Neeta Haresh Goel", "Zarana N Patel"]},
  {"groupNumber": 5, "captains": ["Parushi Tolia", "Neeta Asher"], "members": ["Bhairavi D. koradia", "Bharati Nandlal Tolia", "Deval Hemant Tolia", "Kalpana J. Tolia", "Kusuma Bhupendra Desai", "Lata Atul Tolia", "Meena Jayaprakash Ved", "Neeta Satish Asher", "Parushi Sanjay Tolia", "Sridevi Praful  Tanna"]},
  {"groupNumber": 6, "captains": ["Jyoti Jasapara", "Alka Dilip Shah"], "members": ["Alka D. Shah", "Atula A. Vaidya", "Bhavana Mahesh Prajapati", "Hansa Babulal Baria", "Jyoti Dhiresh Jasapara", "Kavita Ashok Vakharia", "Nirupama S. Soni", "Rasila Satish Raichura", "Rekha A. Rathod", "Rekha K Vaidya"]},
  {"groupNumber": 7, "captains": ["Bhairavi Hasmukh Vora", "Saryu Ben Kamdar"], "members": ["Bhairavi Hasmukh Vora", "Bhanu Subhash Shah", "Hansa Ben Dhanji Shah", "Harsha J. Patel", "Manjula Shantilal Keniya", "Meena Kirit Shah", "Naliniben B . Sanghani", "Reena Kishore Patel", "Saroj Dinesh Shah", "Saryu Ben Kamdar"]},
  {"groupNumber": 8, "captains": ["Kokila Pravin Pujara", "Parul Tushar Kikani"], "members": ["Aarti Ketan Shah", "Bhagwati M Sanghrajka", "Bhavna Rohit Shah", "Chetna H. Shah", "Daksha Dilip Shah", "Kokila Pravin Pujara", "Parul Tushar Kikani", "Prachi Janak Kikani", "Pragna Bharatkumar Shah", "Urmila P Pujara"]},
  {"groupNumber": 9, "captains": ["Gita Chandrakant Patel", "Heena V. Patel"], "members": ["Alpa Jitesh Dave", "Dheera Rakesh Pandya", "Gita Chandrakant Patel", "Heena V. Patel", "Jayna Nirav Pandya", "Jayshree Satish Vyas", "Manisha M. Patel", "Panna Kunal Majithia", "Smita Dinesh Patel", "Sonal Vijay Suchak"]},
  {"groupNumber": 10, "captains": ["Bhavana Tanna", "Minal Rajesh Shah"], "members": ["Apurvi Mihir Jobanputra", "Bhagavati N. Bhatt", "Bharati B. Bhatt", "Bhavana Tanna", "Hemangini Hemant Khant", "Jyotiben J Thakkar", "Kalpana Shailesh Bavishi", "Kanchan Mukesh Thakker", "Minal Rajesh Shah", "Nirmala V. Thacker"]},
  {"groupNumber": 11, "captains": ["Heena Sachin Bhimani", "Charu Hemant Shah"], "members": ["Aditi Ashok Mehta", "Chanda Rajpal Abhaychand", "Charu Hemant Shah", "Deepali Utpal Shah", "Devangi Ketan Shah", "Heena Sachin Bhimani", "Meena Prasanth Vyas", "Monica Manish Shah", "Neeta Ashwin Shah", "Parul Tejpal Shah"]},
  {"groupNumber": 12, "captains": ["Akshika Bhavin Parekh", "Simpal Anish Raichura"], "members": ["Aashita Vikas Zaveri", "Akshika Bhavin Parekh", "Anamika Jayesh Padhiar", "Avani Vipulkumar Acharya", "Bina Harish Indra", "Chamy V Joshi", "Ekta Hirdy Shah", "Pratiksha Vipul Joshi", "Shakuntala H", "Simpal Anish Raichura"]},
  {"groupNumber": 13, "captains": ["Sharmishta R Shah", "Beena Kamal Shah"], "members": ["Beena Kamal Shah", "Hiral K. Sangvi", "Ishita Chitan Shah", "Ishita Ritesh Shah", "Kinjal Kalpesh Shah", "Manisha Rupesh Patel", "Pallavi Pradeep Mavani", "Pragna Karthik Sangvi", "Ramila Bhanuchadna Shah", "Sharmishta R Shah"]},
  {"groupNumber": 14, "captains": ["Kanta K. Patel", "Brinda Rohit Soni"], "members": ["Bharati V. Patel", "Bhavna A. Shah", "Brinda Rohit Soni", "Chhaya G. Rawal", "Kalpana S. Patel", "Kanta K. Patel", "Kanta Valji Patel", "Kastur K. Patel", "Neeta M. Patel", "Rashmi Mahesh Joshi"]},
  {"groupNumber": 15, "captains": ["Jyoti Krishnakumar Jobanputra", "Latha Rajnikant Karia"], "members": ["Harshidaa Dhiresh Raichura", "Heena Acharya", "Jyoti Krishnakumar Jobanputra", "Kashmira Hansakumar Pawani", "Kavita Raichura", "Latha Rajnikant Karia", "Sadhana Kiran Raichura", "Urmila Dattani", "Vandana Arun Raichura", "Veena Hemant Thakker"]},
  {"groupNumber": 16, "captains": ["Deepti Chetan Shah", "Seema P Shah"], "members": ["Beena Mukesh Sanghani", "Bhanumati J Shah", "Charu D. Shah", "Deepti Chetan Shah", "Harsha Bharat Shah", "Meena N Ruparelia", "Preeti Sanjay Shah", "Seema P Shah", "Sharmila Vikash Shah", "Trupti Amrish Parikh"]},
  {"groupNumber": 17, "captains": ["Ranjan Shasikant Kotecha", "Heena Bipin Tanna"], "members": ["Bhavika Dhruv Desai", "Hansa Amirtala Parir", "Heena Bipin Tanna", "Nirupama Shingala", "Parul Vishnu Mehta", "Rajshri S Pavani", "Ranjan B. Desai", "Ranjan Shasikant Kotecha", "Rupal Ramesh Ganatra", "Sarla Y. Samani"]},
  {"groupNumber": 18, "captains": ["Tanuja Paresh Tolia", "Jyoti Nilesh Shah"], "members": ["Deepa Bharat Shah", "Jyoti Nilesh Shah", "Kalpana Aiya", "Kishori Arvind Shah", "Meghna Nirav Shah", "Mita Bhavin Shah", "Pallavi Kavish Shah", "Sandhya Ashok Shah", "Sangeeta Rajesh Shah", "Tanuja Paresh Tolia"]},
  {"groupNumber": 19, "captains": ["Vaishali Mayur Shah", "Rupal Tusar Shah"], "members": ["Bhumika Ashok Patel", "Hasmita Ajay Shah", "Jashavanti Mavji", "Priyanka Sailesh Patel", "Ragini Vimal Shah", "Rupal Tusar Shah", "Seeta Prakash Mepani", "Shital S. Shah", "Sonal Rahul Shah", "Vaishali Mayur Shah"]},
  {"groupNumber": 20, "captains": ["Kanchan Sanjay Patel", "Tulja Kantilal Patel"], "members": ["Bhagvati Nathu Patel", "Damyanthi V. Patel", "Geeta Mahendran Patel", "Heena Kaushik Patel", "Hemlata Shantilal Patel", "Kanchan Sanjay Patel", "Latha Sachin Patel", "Radha Jayantilal Patel", "Rekha Dinesh Patel", "Tulja Kantilal Patel"]},
  {"groupNumber": 21, "captains": ["Anjani Paresh Raichura", "Namita Prakash Majethia"], "members": ["Anjani Paresh Raichura", "Kamini Uday Asher", "Leena Bharat Khakkar", "Namita Prakash Majethia", "Pooja Kalpesh Majethia", "Preeti P Asher", "Roopa Pratap Raichura", "Sadhana Suresh Mangaldas", "Tejal Chirag Majethia", "Vinita V Thakkar"]},
  {"groupNumber": 22, "captains": ["SUDHA V DAGLI", "Falguni A. Gattani"], "members": ["Bhakti Vikash Mehta", "Bindu Ketan Shah", "Ella D. Sanghani", "Falguni A. Gattani", "Ila Mahendra Kikani", "Krupa Ritesh Sangani", "Parul Nilesh Shah", "Poonam S.", "Shradha Shah", "Sudha Vinod Dagli"]},
  {"groupNumber": 23, "captains": ["Aarti Chintan Lodaya", "Dhara Virat Popat"], "members": ["Aarti Chintan Lodaya", "Bharati Modi", "Dhara Virat Popat", "Heena H. Popat", "Jyoti V. Popat", "Payal Siddharat Popat", "Renuka Jagdish Bhojani", "Riddhi Nirav Parikh", "Rupa Jayant Popat", "Urvashi Nitin Lodaya"]},
  {"groupNumber": 24, "captains": ["Aruna Mukund Dave", "Ranjanben Mehta"], "members": ["Aruna Mukund Dave", "Diti Priyank Mavai", "Harshada Kantilal Pandya", "Ila Lalit kikani", "Jignasa Siddharth Mehta", "KShrinee Raichura", "Leena Kaushi Mavani", "Nayna Yogesh Metha", "Purvi Lomesh Parekh", "Ranjan Rashmi Mehta"]},
  {"groupNumber": 25, "captains": ["Bhairvi Rajiv Sheth", "Anjana Nirov sheth"], "members": ["Anjana Nirav Sheth", "Bhairvi Rajiv Sheth", "Falguni Guvrav Shah", "Jigna Priyesh Mehta", "Ketki Asher", "Mittal Megal Somiya", "Neelam Harish Shah", "Roopali K Patel", "Sandhya Atul Asher", "Vinnie Karthik shah"]},
  {"groupNumber": 26, "captains": ["Divya Hiren Thakker", "Meena Gopalakrishnan"], "members": ["Divya Hiren Thakker", "Jaya Navin Kariya", "Latha Pravin Aiya", "Manjula S. Patel", "Meena Gopal", "Nisha Jayesh Pavani", "Pallavi Anish Patel", "Pratima V. Kotecha", "Rashmi Rajesh Kariya", "Vishakha  Niranjan Thakker"]},
  {"groupNumber": 27, "captains": ["Minakshi Naresh Vyas", "Parul Hitesh Solanki"], "members": ["Anju Mukesh Patel", "Bharati Ganshyam Katheriya", "Bhavika Jayantbhai Baboriya", "Chandrika Dilip Patel", "Jyoti Kirthi Sangani", "Manisha Devang Thakkar", "Minakshi Naresh Vyas", "Mona K. Vyas", "Parul Hitesh Solanki", "Purva Rahul Dhruv"]},
  {"groupNumber": 28, "captains": ["Rekha Kishor Patel", "Jagruti Jitesh Patel", "Rita Deepak Patel"], "members": ["Bhavana Bhupendra Patel", "Devi Karmsi Patel", "Jagruti Jitesh Patel", "Jayshree K. Patel", "Maniben Jayanthilal Patel", "Narmada Jayantilal Patel", "Narmada Mohan Patel", "Preeti Suresh Patel", "Rekha Kishor Patel", "Rita Deepak Patel"]},
  {"groupNumber": 29, "captains": ["Shital H Savani"], "members": ["Bhanumati Nandlal Patel", "Kinna Jayesh Patel", "Manasi P Patel", "Megal Shyam Patel", "Niketa Vipul Patel", "Pooja K Kanteliya", "Rekha D Kanteliya", "Shital Hiran Savani", "Sonal Manish Parivar", "Kajal Sanjay Patel"]},
  {"groupNumber": 30, "captains": ["Divya Pankaj Tarwadi", "Kruti K Metha"], "members": ["Divya Pankaj Tarwadi", "Kruti K Metha", "Manjula Dilip Joshi", "Meena Prashant Pandya", "Meeta Harshad Joshi", "Meghna Mitesh Dave", "Neela Hiren Desai", "Neeta Bhupendra Desai", "Rakhi Balkrishna Mehta", "Seema Vivek Radia"]},
  {"groupNumber": 31, "captains": ["Leena Hemant Doshi", "Shruti A Shah"], "members": ["Amita Rishikesh Khakkar", "Harsha A Shah", "Hetal  Vikee Shah", "Leena Hemant Doshi", "Neena Bimal Shroff", "Priti T. Shah", "Richa Bharat Tanna", "Seema Uday Shroff", "Sheetal Anand Powani", "Shruti A Shah"]},
  {"groupNumber": 32, "captains": ["Rajni J Paleja", "Dharini U. Sharma"], "members": ["Dharini U. Sharma", "Hansa Jayendra Paleja", "Hira Hansraj Patel", "Jaya Kishore Patel", "Kajal Kaushik Majithia", "Meenal Amar Asher", "Rajni Jayendra Paleja", "Revati Rajesh Raichura", "Rupal Kamlesh Modi", "Smita Dinesh Thacker"]},
  {"groupNumber": 33, "captains": ["Hiral Bhavik Vora", "Virti C Savani"], "members": ["Hiral Bhavik Vora", "Jalpa Dipesh Shah", "Mamta Ketan Lalan", "Pooja Ashit Shah", "Prachi Darshil Tolia", "Priya H Bavisi", "Ragini Kirit Shah", "Shilpa Hakkar", "Vandana Vora", "Virti C Savani"]},
  {"groupNumber": 34, "captains": ["JALPA DESAI", "Rupal Amish  Sheth"], "members": ["Aneri Pratik Daga", "Deepali N Shah", "Ektha Carthik Sanghani", "Jalpa R Desai", "Mona B Shah", "Nehal Shah", "Rupal  Vipul Shah", "Rupal Amish  Sheth", "Sonal Shah", "Yutal Manish Momaya"]},
  {"groupNumber": 35, "captains": ["Beena Nitin Sheth", "Jigha Alkesh Sheth"], "members": ["Beena Nitin Sheth", "Bhavana Paresh Sheth", "Bhavana Sukhadia", "Chaya Prakash Kapasi", "Daksha Nishil Jatakiya", "Jasmine Virer Momaya", "Jigha Alkesh Sheth", "Naina Uday Sukhadiya", "Rashmi Kartik Momaya", "Varsha Vipul Sukhadiya"]},
  {"groupNumber": 36, "captains": ["Manasi Harsh Patel", "Nikita Deep Sheth"], "members": ["Devika Milind Patel", "Dharti Patel", "Disha R Patel", "Jalpa Rohit Zalariya", "Karisma Manav Patel", "Manasi Harsh Patel", "Nikita Deep Sheth", "Nirali D . Kapasi", "Pallaviben B.", "Pooja Kunal Sheth"]},
  {"groupNumber": 37, "captains": ["Zeel J Dattani", "Mahima Parag Somiya"], "members": ["Dhruvi Manek", "Disha Jitesh Sangani", "Jagruti Jignesh Patel", "Komal Alpesh Sangani", "Mahima Parag Somiya", "Minal Sunil Patel", "Pinal Dave", "Preksha Tanna", "Sunita Ketan Kariya", "Zeel J Dattani"]},
  {"groupNumber": 38, "captains": ["Tanya Shah", "Komal Chandresh Shah"], "members": ["Chhaya Vardharajan", "Dhruvi J Shah", "Diksha V Desai", "Harsha Sanjaybhai Shukla", "Ketki K . Shah", "Komal Chandresh Shah", "Komala J. Shah", "Manasi Abhay Davey", "Sneha Kaneria", "Tanya Jinang Shah"]},
  {"groupNumber": 39, "captains": ["Punta Chandrakant Shah", "Jayshree H. Shah"], "members": ["Asha Kirit Mehta", "Daksha Chitrang Shah", "Devanshi C Doshi", "Heena J Doshi", "Jasmin Dinesh Shah", "Jayshree H. Shah", "Neepaben Sanghavi", "Nita Bhupatrai", "Punta Chandrakant Shah", "Sajal R Shah"]},
  {"groupNumber": 40, "captains": ["Urmila Pravin Adroja", "Krupa P. Vachhani"], "members": ["Bhavana Dilip Patel", "Bhavana M. Kalariya", "Gulab Mukesh Makwana", "Harsha Pravin Patel", "Krishna Ketan Vachani", "Krupa P. Vachhani", "Sevina J. Kaneria", "Shobhana Kaushik Vachani", "Urmila Pravin Adroja", "Vijaya Kantilal Savani"]},
  {"groupNumber": 41, "captains": ["Heena Bharat Shah", "Sudha Rajesh Mehta"], "members": ["Beena J Shah", "Bhavini Jatin Mehta", "Bina Nailesh Shah", "Heena Bharat Shah", "Hemalatha J. Shah", "Ila V. Desai", "Meena Kirit Savani", "Nanda M. Desai", "Pushpa L. Savani", "Sudha Rajesh Mehta"]},
  {"groupNumber": 42, "captains": ["Aarti Vimal Radia", "Rita Mayur Parikh"], "members": ["Aarti Vimal Radia", "Kamini Vasani", "Meena Kanaiyalal Parikh", "Pallavi Majithia", "Praveena Vijay Radia", "Rita Mayur Parikh", "Ruthvi Gopal", "Seema Umesh Radia", "Seetha Radia", "Vandana Jairaj Kothari"]},
  {"groupNumber": 43, "captains": ["Pushpa Dinesh Patel", "Laxmi Naresh Patel (Pokar)"], "members": ["Bhagvati N Patel", "Bharti Kirti Patel", "Jashoda G. Patel", "Kala Yeshwant Patel", "Kalpana Sanjay Patel", "Latha Nilesh Patel (Pokar)", "Laxmi Naresh Patel (Pokar)", "Pushpa Dinesh Patel", "Shiela Babulaa Patel", "Suman Anil Patel"]},
  {"groupNumber": 44, "captains": ["Kirthi D Lodaya", "Divya Nitin Sejpal"], "members": ["Ashvini Modi", "Bhanumati Shah", "Divya Nitin Sejpal", "Hetal A Sanghrajka", "Kirthi D Lodaya", "Meera J. Davda", "Pinky Hiren Shah", "Rajeshri Patel", "Sheela Sukant Desai", "Tulika Nilesh Shah"]},
  {"groupNumber": 45, "captains": ["Binal Saurin Shah", "Komal Paresh Shah"], "members": ["Binal Saurin Shah", "Devyani D Shah", "Komal Paresh Shah", "Naina Niketu Shah", "Nisha N. Kapasi", "Rani B Shah", "Rinky V .Shah", "Roopal Shah", "Seema Jatin Shah", "Palakh N Shah (X)"]},
  {"groupNumber": 46, "captains": ["Ketana Dinesh Vasani", "Panna Anil Padhiar"], "members": ["Alpa Amar Padhiar", "Dhanalakshmi Raichura", "Geeta Nimish Raichura", "Jyoti Nalin Zaveri", "Ketana Dinesh Vasani", "Nisha A Shah", "Panna Anil Padhiar", "Shobha Kamlesh Padhiar", "Tejas Ambrish Pathak", "Vandana M. Patel"]},
  {"groupNumber": 47, "captains": ["Bharati Jayant Ohja", "Harshida H Vagadia"], "members": ["Asha A. Shah", "Bharati Jayant Ohja", "Deepika N. Dave", "Dina Mahendra Sanghani", "Harshida H Vagadia", "Rekha Hasmukh Sangani", "Renuka D Patel", "Ranjanbala Yashwant Dave", "Savitri Mahendra Dave", "Vijaya K. Umarania"]},
  {"groupNumber": 48, "captains": ["Bhakti Harish Samani", "Anitha  Anoop Sundrani"], "members": ["Alpa Jigar Patel", "Ambika Hemanth Rathode", "Anitha  Anoop Sundrani", "Archana Dinesh Rathode", "Bhakti Harish Samani", "Darshana B Thacker", "Kavita Bhupesh Samani", "Nirmala V Rathode", "Nisha Depesh Dawda", "Thrupthi Pooran Jaypee"]},
  {"groupNumber": 49, "captains": ["Dharani Panchamia", "Monika Shah (X)"], "members": ["Ami Madhusudan Vyas", "Dharani Panchamia", "Kinjal Zaveri", "Lata Sonpal", "Mona U Kikani", "Monika Shah (X)", "Nimisha Joshi", "Priyanka Suraj", "Varsha Shailesh Shah", "Viral G Shah (X)"]},
  {"groupNumber": 50, "captains": ["Bharati Sangani", "Kalpa Shankar Iyer"], "members": ["Avani Shukla", "Bhanumati B Shah", "Bharati Sangani", "Daksha M. Maniar", "Falun Motipara H", "Hetal K Bhatt (X)", "Kalpa Shankar Iyer", "Kavita Jinesh Shah (X)", "Palak Mavani", "Urmila Kotadia"]},
  {"groupNumber": 51, "captains": ["; HEENA RAHUL", "Pallavi Sachin Kotecha"], "members": ["Alpa Chandresh Panchal", "Avani sujal Shah", "Deepti samir Dave", "Heena Rahul Kotecha", "Jigna V Kapasi", "Meeta Divyesh Thakker", "Pallavi Sachin Kotecha", "Rupal Piyush Thakker", "Seema Rajesh Shah", "Trupti Nikunj Ganatra"]},
  {"groupNumber": 52, "captains": [], "members": ["Chhaya. S  (X)", "Jimisha Joshi", "Savitha Jay Tanna  (X)", "Jagruti Shah", "Ruchi Milesh Parmar"]},
  {"groupNumber": 60, "captains": [], "members": ["Gita Lalit Paleja (NC)", "Jayaben Somaya", "Sarla Pujara", "Shobhana Pradeep Mehta", "Yoshoda Joshi", "Rajeshree Thakker"]}
]

# Write to file
with open('/home/developer/Documents/mm/data/cookingGroups.json', 'w', encoding='utf-8') as f:
    json.dump(groups_data, f, indent=2, ensure_ascii=False)

print(f"Created cookingGroups.json with {len(groups_data)} groups")
